config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"}
#blogsにcommentsをネストはマスト
  resources :blogs, only: [:index,:show, :new,:create, :edit, :update, :destroy] do
    member do
      get :liking_users
    end
    #resources :likes
  resources :comments
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create, :confirm ] do
    collection do
      post :confirm
    end
  end

post '/like/:blog_id' => 'likes#like', as: 'like'
delete '/unlike/:blog_id' => 'likes#unlike', as: 'unlike'

root 'top#index'
#タスクはユーザに紐付くため、ルーティングはユーザのルーティング下にネスト（階層化）させる必要があるため
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_blogs
  end
  resources :tasks
  resources :submit_requests , shallow: true do
    get 'approve'
    get 'unapprove'
    get 'reject'
    collection do
      get 'inbox'
    end
  end
end

  resources :relationships, only: [:create, :destroy, :edit, :update] do
  end

  resources :conversations do
    resources :messages
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end
  def index
    @messages = @conversation.messages
  if @messages.length > 10
    @over_ten = true
    @messages = @messages[-10..-1]
  end

  if params[:m]
    @over_ten = false
    @messages = @conversation.messages
  end

  if @messages.last
    if @messages.last.user_id != current_user.id
     @messages.last.read = true
    end
  end
  @message = @conversation.messages.build
  end

  def create
    @message = @conversation.messages.build(message_params)
   if @message.save
    redirect_to conversation_messages_path(@conversation)
   end
  end

  private
  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/index.html.erb
<% if @over_ten %>
  <%= link_to '以前のメッセージ', '?m=all' %>
<% end %>

<div class="ui segment">
  <% @messages.each do |message| %>
    <% if message.body %>
      <% user = User.find(message.user_id) %>
      <div class="item">
        <div class="content">
          <div class="header"><strong><%= user.name %></strong> <%= message.message_time %></div>
          <div class="list">
            <div class="item">
              <i class="right triangle icon"></i>
              <%= message.body %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= form_for [@conversation, @message], html: {class: "ui reply form"} do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
    <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
  <div>
    <%= f.submit "メッセージを送る" , class: 'btn btn-primary btn-block' %>
  </div>
<% end %>
  <div>
    <%= link_to "ユーザー一覧", users_path %> |
    <%= link_to "メッセージ一覧", conversations_path %>
  </div>