config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"}
#blogsにcommentsをネストはマスト
  resources :blogs, only: [:index,:show, :new,:create, :edit, :update, :destroy] do
    member do
      get :liking_users
    end
    #resources :likes
  resources :comments
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create, :confirm ] do
    collection do
      post :confirm
    end
  end

post '/like/:blog_id' => 'likes#like', as: 'like'
delete '/unlike/:blog_id' => 'likes#unlike', as: 'unlike'

root 'top#index'
#タスクはユーザに紐付くため、ルーティングはユーザのルーティング下にネスト（階層化）させる必要があるため
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_blogs
  end
  resources :tasks
  resources :submit_requests , shallow: true do
    get 'approve'
    get 'unapprove'
    get 'reject'
    collection do
      get 'inbox'
    end
  end
end

  resources :relationships, only: [:create, :destroy, :edit, :update] do
  end

  resources :conversations do
    resources :messages
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :charge, class_name: 'User', foreign_key: 'charge_id'
  validates :title, presence: true
  has_many :submit_requests, dependent: :destroy
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.where(user_id: params[:user_id]).where.not(done: true).order(deadline: :desc)
    @user = User.find(params[:user_id])
  end

  def show
     @user = User.find(params[:user_id])
     @charger = User.find(@task.charge_id)
     redirect_to(user_tasks_path(current_user)) unless current_user == @charger || current_user == @user
  end

  def new
     @task = Task.new(user_id: params[:user_id], charge_id: params[:user_id])
  end


  def edit
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to user_tasks_url, notice: 'タスクを登録しました。' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to user_tasks_url, notice: 'タスクを編集しました。' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to user_tasks_url, notice: 'タスクを削除しました。' }
      format.json { head :no_content }
    end
  end

  private
  def set_task
      @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:user_id, :title, :content, :deadline, :charge_id, :done, :status)
  end

  def correct_user
    @user = User.find(params[:user_id])
    redirect_to(user_tasks_path(current_user)) unless current_user == @user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@task.user, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :charge_id %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="field">
    <%= f.select :status, [["未着手", "0"], ["対応中", "1"]] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Task編集</h1>

<%= render 'form' %>

<%= link_to 'Show', user_task_path(@task.user, @task) %> |
<%= link_to 'Back', user_tasks_path(@task.user)%>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Tasks 一覧</h1>
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <table class="table">
      <thead>
        <tr>
          <th>User</th>
          <th>Title</th>
          <th>Content</th>
          <th>Deadline</th>
          <th>Charge</th>
          <th>Done</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

  <tbody>
    <% @tasks.each do |task| %>
        <tr>
          <% if task.user.name.blank? %>
            <td><%= "未登録" %></td>
          <% else %>
            <td><%= task.user.name %></td>
          <% end %>

          <td><%= task.title %></td>
          <td><%= simple_format task.content %></td>
          <td><%= task.deadline %></td>
          <td><%= task.charge_id %></td>
          <td><%= if task.done? then "完了" else "未完了" end %></td>
          <td><%= task.status == 1? "対応中" : "未着手" %></td>
          <td><%= link_to '詳細', user_task_path(task.user, task) %></td>
          <td><%= link_to '編集', edit_user_task_path(task.user, task) %></td>
          <td><%= link_to '削除', user_task_path(task.user, task), method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

    <br>
  </div>
</div>
<%= link_to 'New Task', new_user_task_path(@user) %>

app/views/tasks/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>新規タスク作成</h2>
       <%= render 'form' %>
  </div>
</div>
<%= link_to '戻る', user_tasks_path(@task.user), class: 'btn btn-default' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @task.user.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>Charge:</strong>
  <%= @task.charge.name %>
</p>

<p>
  <strong>Done:</strong>
  <%= if @task.done? then "Complete" else "incomplete" end  %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status == 1? "対応中" : "未着手" %>
</p>

<%= link_to 'Edit', edit_user_task_path(@task.user, @task)  %> |
<%= link_to 'Back', user_tasks_path(@task.user) %>