config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"}
#blogsにcommentsをネストはマスト
  resources :blogs, only: [:index,:show, :new,:create, :edit, :update, :destroy] do
    member do
      get :liking_users
    end
    #resources :likes
  resources :comments
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create, :confirm ] do
    collection do
      post :confirm
    end
  end

post '/like/:blog_id' => 'likes#like', as: 'like'
delete '/unlike/:blog_id' => 'likes#unlike', as: 'unlike'

root 'top#index'
#タスクはユーザに紐付くため、ルーティングはユーザのルーティング下にネスト（階層化）させる必要があるため
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_blogs
  end
  resources :tasks
  resources :submit_requests , shallow: true do
    get 'approve'
    get 'unapprove'
    get 'reject'
    collection do
      get 'inbox'
    end
  end
end

  resources :relationships, only: [:create, :destroy, :edit, :update] do
  end

  resources :conversations do
    resources :messages
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

mount_uploader :avatar, AvatarUploader


has_many :blogs,dependent: :destroy
has_many :comments, dependent: :destroy
has_many :relationships, foreign_key: "follower_id", dependent: :destroy
has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
has_many :followed_users, through: :relationships, source: :followed
has_many :followers, through: :reverse_relationships, source: :follower
has_many :tasks, dependent: :destroy
has_many :submit_requests, dependent: :destroy
has_many :likes
has_many :like_blogs, through: :likes, source: :blog

#validates :name, presence: true

def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20],
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end



  def self.create_unique_string
      SecureRandom.uuid
  end

#指定のユーザをフォローする
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

#フォローしているかどうかを確認する
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

#指定のユーザのフォローを解除する
  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

#「つながっているユーザを取得する」
  def friend
    followers & followed_users
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
     # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end




end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :correct_user, only: [:edit,:update]
before_action :set_user, only: [:show, :edit, :update, :like_blogs]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @followed_users = @user.followed_users
    @followers = @user.followers
    @blogs = @user.blogs
  end

  def edit
  end

  def update
  end

  def like_blogs
    @blogs = @user.like_blogs
    @title = "いいね！一覧"
    render :show
  end

  private

    def set_user
    @user= User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end

    def correct_user
      user = User.find(params[:id])
      if !current_user?(user)
        redirect_to root_path, alert: '許可されてないページです'
      end
    end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: "btn btn-large btn-primary" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "つながりを解除", class: "btn btn-large" %>
    <% end %>
  <% end %>
</div>

app/views/users/_user.html.erb
<div class="container-child col-md-2 col-sm-4 col-xs-6 ">
  <%= link_to user.name, user_path(user)  %>

  <%= profile_img(user) %>

  <% if user != current_user %>

 <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
  <%= render partial: 'follow_form', locals: { user: user }  if signed_in? %>
  <% else %>
    <%= link_to 'ユーザー編集', edit_user_registration_path, class: 'btn btn-info' %>
  <% end %>
</div>


<!--  <%= user.email %> -->

app/views/users/index.html.erb
<div class="container">
  <h1>ユーザー</h1>
 <%= render @users %>
</div>

app/views/users/show.html.erb
<h2>ユーザー詳細ページ</h2>

<aside class="sidebar">
  <section>
    <span class="label">ユーザー</span>
    <h2 class="user-info"><%= @user.name %></h2>
  </section>

  <section>
    <span class="label">プロフィール画像</span>
    <h3 class="user-info">
      <%= profile_img(@user) %>
    </h3>
  </section>

  <h4>フォローしているユーザー</h4>
    <% @followed_users.each do |user| %>
            <ul class="usershow">
              <li><%= profile_img(user) %></li>
              <!-- <li><%= user.email %></li> -->
              <li><%= user.name %></li>
            </ul>
    <% end %>

  <h4>フォローされているユーザー</h4>
    <% @followers.each do |user| %>
      <ul class="usershow">
        <li><%= profile_img(user) %></li>
        <!-- <li><%= user.email %></li> -->
        <li><%= user.name %></li>
      </ul>
    <% end %>
</aside>
<h2><%= link_to @user.likes.count, like_blogs_user_path(@user.id) %>個の投稿にいいね！しています。</h2>
<ul class="blogs">
  <h2><%= @title %></h2>
  <%= render @blogs %>
</ul>